## methods_page.R -------------------------------------------------------------
##
## The "Methods & mathematics" tab. Written for someone meeting this problem for
## the first time: intuition first, then notation, then a worked example that
## every method is put through, then the model behind each method.
##
## Equations are LaTeX rendered by KaTeX; if the CDN is unreachable the raw
## LaTeX stays legible rather than disappearing.
## ---------------------------------------------------------------------------

katex_head <- function() {
  tagList(
    tags$link(rel = "stylesheet",
              href = "https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css",
              crossorigin = "anonymous"),
    tags$script(defer = NA, src = "https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js",
                crossorigin = "anonymous"),
    tags$script(defer = NA,
                src = "https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js",
                crossorigin = "anonymous",
                onload = "renderMathInElement(document.body,{delimiters:[
                  {left:'\\\\[',right:'\\\\]',display:true},
                  {left:'\\\\(',right:'\\\\)',display:false}],throwOnError:false});"),
    tags$script(HTML(
      "document.addEventListener('shiny:value', function(){
         if (window.renderMathInElement) setTimeout(function(){
           renderMathInElement(document.body,{delimiters:[
             {left:'\\\\[',right:'\\\\]',display:true},
             {left:'\\\\(',right:'\\\\)',display:false}],throwOnError:false});
         }, 30);
       });")),
    tags$style(HTML("
      .m-body{max-width:47rem;}
      .m-body p{margin:.7rem 0;line-height:1.62;}
      .m-lead{font-size:1.02rem;color:#33474d;}
      .m-eq{margin:1rem 0;overflow-x:auto;padding:.2rem 0;}
      .m-h{font-weight:600;color:#12262a;margin:2.4rem 0 .5rem;font-size:1.15rem;
        padding-top:.9rem;border-top:1px solid #e8efed;}
      .m-h:first-child{border-top:0;padding-top:0;margin-top:.2rem;}
      .m-sub{font-weight:600;color:#12262a;margin:1.5rem 0 .35rem;font-size:.97rem;}
      .m-tag{display:inline-block;font-size:.66rem;font-weight:700;letter-spacing:.08em;
        text-transform:uppercase;padding:.16em .55em;border-radius:2px;margin-left:.5rem;
        vertical-align:.15em;}
      .m-tag.rec{background:#f6eddc;color:#a8762a;}
      .m-tag.chk{background:#e3efef;color:#0f6b73;}
      .m-def{border-left:2px solid #dae4e2;padding-left:1rem;margin:1rem 0;font-size:.93rem;
        color:#4a6067;}
      .m-def b{color:#12262a;}
      table.m-tbl{border-collapse:collapse;margin:1rem 0;font-size:.88rem;width:100%;}
      table.m-tbl th{text-align:left;font-size:.7rem;letter-spacing:.06em;text-transform:uppercase;
        color:#6b7a80;font-weight:600;padding:.2rem .9rem .35rem 0;border-bottom:1px solid #dae4e2;}
      table.m-tbl td{padding:.35rem .9rem .35rem 0;border-bottom:1px solid #eef3f2;
        vertical-align:top;}
      table.m-tbl td:first-child{white-space:nowrap;}
      .m-note{background:#f6eddc;border-left:3px solid #a8762a;padding:.7rem 1rem;
        margin:1.1rem 0;font-size:.9rem;border-radius:0 3px 3px 0;}
      .m-plain{background:#eef5f0;border-left:3px solid #4a7c59;padding:.7rem 1rem;
        margin:1.1rem 0;font-size:.92rem;border-radius:0 3px 3px 0;}
      .m-plain b{color:#2f6b4f;}
      .m-toc a{display:block;padding:.22rem 0;font-size:.86rem;text-decoration:none;}
      .m-toc .m-toc-sec{font-size:.66rem;letter-spacing:.08em;text-transform:uppercase;
        color:#8fa3a6;font-weight:600;margin:.8rem 0 .1rem;}
      table.m-ex{border-collapse:collapse;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;
        font-size:.84rem;margin:.9rem 0;}
      table.m-ex th{font-family:system-ui,sans-serif;font-size:.68rem;letter-spacing:.05em;
        text-transform:uppercase;color:#6b7a80;padding:.2rem .75rem .35rem;
        border-bottom:1px solid #dae4e2;text-align:center;}
      table.m-ex th:first-child{text-align:left;}
      table.m-ex td{padding:.3rem .75rem;text-align:center;border-bottom:1px solid #eef3f2;}
      table.m-ex td:first-child{text-align:left;font-family:system-ui,sans-serif;
        font-size:.82rem;color:#4a6067;}
      table.m-ex .diff{background:#f6eddc;color:#a8762a;font-weight:600;}
      table.m-ex .miss{background:#eef3f2;color:#8fa3a6;}
    "))
  )
}

.eq <- function(x) tags$div(class = "m-eq", paste0("\\[", x, "\\]"))
.h  <- function(x, id = NULL, tag = NULL, tagclass = "rec")
  tags$div(class = "m-h", id = id, x,
           if (!is.null(tag)) tags$span(class = paste("m-tag", tagclass), tag))
.s  <- function(x) tags$div(class = "m-sub", x)
.p  <- function(...) tags$p(...)
.plain <- function(...) tags$div(class = "m-plain", tags$b("In plain words. "), ...)

## the worked example every method is put through
EX_LOCI <- c("L1", "L2", "L3", "L4", "L5", "L6")
EX_A    <- c("A/G", "C/C", "T/T", "A/A", "G/T", "C/T")
EX_B    <- c("A/A", "C/C", "T/T", "A/A", "G/T", "--")
EX_CLS  <- c("diff", "", "", "", "", "miss")

## render a small mock file layout
.file_table <- function(header, rows, note_cols = character(0)) {
  cls <- function(h) if (h %in% note_cols) "diff" else ""
  tags$table(class = "m-ex",
    tags$thead(tags$tr(lapply(header, function(h) tags$th(class = cls(h), h)))),
    tags$tbody(lapply(rows, function(r)
      tags$tr(Map(function(v, h) tags$td(class = cls(h), v), r, header)))))
}


.example_table <- function() {
  tags$table(class = "m-ex",
    tags$thead(tags$tr(tags$th("Locus"), lapply(EX_LOCI, tags$th))),
    tags$tbody(
      tags$tr(tags$td("Sample A"),
              Map(function(g, c) tags$td(class = c, g), EX_A, EX_CLS)),
      tags$tr(tags$td("Sample B"),
              Map(function(g, c) tags$td(class = c, g), EX_B, EX_CLS)),
      tags$tr(tags$td("Same?"),
              tags$td(class = "diff", "no"), tags$td("yes"), tags$td("yes"),
              tags$td("yes"), tags$td("yes"), tags$td(class = "miss", "not typed"))))
}


methods_panel <- function() {
  nav_panel(
    "Methods", icon = icon("book-open"),
    layout_columns(
      col_widths = c(3, 9),

      card(card_header("Contents"), class = "m-toc",
        tags$div(class = "m-toc-sec", "Start here"),
        tags$a(href = "#m-problem", "The problem"),
        tags$a(href = "#m-format", "Your file format"),
        tags$a(href = "#m-notation", "Notation"),
        tags$a(href = "#m-example", "A worked example"),
        tags$a(href = "#m-prep", "Preparing the data"),
        tags$div(class = "m-toc-sec", "The methods"),
        tags$a(href = "#m-exact", "1. Exact match"),
        tags$a(href = "#m-thresh", "2. Mismatch threshold"),
        tags$a(href = "#m-genalex", "3. GenAlEx Matches"),
        tags$a(href = "#m-am", "4. allelematch"),
        tags$a(href = "#m-lr", "5. Likelihood ratio"),
        tags$a(href = "#m-sethi", "6. Sethi et al. (2016)"),
        tags$a(href = "#m-space", "7. Adding location"),
        tags$div(class = "m-toc-sec", "Afterwards"),
        tags$a(href = "#m-reps", "Using PCR replicates"),
        tags$a(href = "#m-graph", "From pairs to individuals"),
        tags$a(href = "#m-err", "Measuring error rates"),
        tags$a(href = "#m-cutoff", "Choosing the cutoff"),
        tags$a(href = "#m-set", "Choosing settings"),
        tags$a(href = "#m-glossary", "Glossary of every column"),
        tags$a(href = "#m-refs", "References")),

      card(card_header("Methods & mathematics"), tags$div(class = "m-body",

        # ------------------------------------------------------------ problem
        .h("The problem", id = "m-problem"),
        .p(class = "m-lead",
          "You have collected samples \u2014 scats, hairs, feathers, tissue \u2014 and ",
          "genotyped each one. Several samples may have come from the same animal, ",
          "and you do not know which. Your job is to work out how many animals you ",
          "actually have."),
        .p("If genotyping were perfect this would be a lookup: identical genotype, ",
           "same animal; different genotype, different animal. Three things break that."),
        tags$div(class = "m-def",
          .p(tags$b("Allelic dropout."), " Each animal carries two copies of every ",
             "locus. If it carries two different versions \u2014 a ", tags$i("heterozygote"),
             ", written ", tags$code("A/G"), " \u2014 and only one of them amplifies in the ",
             "PCR, the sample is scored ", tags$code("A/A"), ". Two samples from one animal ",
             "now look different. Dropout is the dominant error in degraded material such ",
             "as scat or hair, where there is very little intact DNA to start with."),
          .p(tags$b("False alleles."), " An allele appears that the animal does not carry, ",
             "usually from a PCR slip or contamination."),
          .p(tags$b("Relatives."), " Siblings inherit from the same two parents, so they ",
             "share a lot of their genome. Two different animals from the same litter can ",
             "look more alike than two samples from one animal that suffered dropout. This ",
             "is the reason a method that only counts differences cannot get the hard cases ",
             "right, and it is why the better methods ask you to say what kind of ",
             "\u201cdifferent animal\u201d you are testing against.")),
        .p("Every method on this page is a different answer to one question: ",
           tags$b("how many differing loci are still consistent with one animal?")),

        # -------------------------------------------------------------- format
        .h("What your file has to look like", id = "m-format"),
        .p(class = "m-lead",
          "One column per locus, and one row per sample — or one row per PCR ",
          "replicate if you want to use those directly. CSV, TSV or Excel. ",
          "Everything else the app works out for itself."),

        .s("Format A — one row per sample"),
        .p("The usual case: you have already collapsed any replicates into a ",
           "consensus genotype, and each sample appears once."),
        .file_table(
          c("SampleID", "Species", "Sex", "LOC01", "LOC02", "LOC03", "LOC04"),
          list(c("WFS_001", "wolf", "XX", "AG", "CC", "00", "CT"),
               c("WFS_002", "wolf", "XY", "AA", "CT", "TT", "CT"),
               c("WFS_003", "coyote", "XX", "AG", "CC", "TT", "00")),
          note_cols = "SampleID"),
        .p("The only column the app truly needs is the sample identifier. ",
           tags$code("Species"), " and ", tags$code("Sex"), " here are ordinary ",
           "extra columns — useful, but named however you like and not ",
           "required."),

        .s("Format B — one row per PCR replicate"),
        .p("If you genotyped each sample more than once, give the app every ",
           "reaction. It will notice the repeated sample identifiers and offer to ",
           "use them directly, which is better than collapsing them first (see ",
           tags$a(href = "#m-reps", "Using PCR replicates"), ")."),
        .file_table(
          c("SampleID", "Rep", "Species", "LOC01", "LOC02", "LOC03", "LOC04"),
          list(c("WFS_001", "a", "wolf", "AG", "CC", "00", "CT"),
               c("WFS_001", "b", "wolf", "AA", "CC", "CT", "CT"),
               c("WFS_001", "c", "wolf", "AG", "00", "00", "CT"),
               c("WFS_001", "consensus", "wolf", "AG", "CC", "00", "CT"),
               c("WFS_002", "a", "wolf", "AA", "CT", "TT", "CT")),
          note_cols = c("SampleID", "Rep")),
        .p("The replicate label column can be called anything; you pick it in the ",
           "sidebar. If your file also carries pre-computed ", tags$code("consensus"),
           " rows, list that label under ", tags$b("Row labels to exclude"),
           " so it is not counted as a fourth reaction. The app finds and ",
           "pre-selects labels like ", tags$code("consensus"), " for you."),
        .plain("Same file, both ways. A file in Format B can be analysed either ",
               "as replicates or collapsed to a consensus, and you can switch ",
               "between the two in the sidebar to see whether it changes anything."),

        .s("How to write a genotype"),
        tags$table(class = "m-tbl",
          tags$thead(tags$tr(tags$th("Thing"), tags$th("Write it like this"), tags$th("Notes"))),
          tags$tbody(
            tags$tr(tags$td("SNP genotype"), tags$td(tags$code("AG"), ", ", tags$code("CC"), ", ", tags$code("T/C")),
                    tags$td("Two alleles in one cell. A separator is optional.")),
            tags$tr(tags$td("Microsatellite"), tags$td(tags$code("120/124"), ", ", tags$code("120|124")),
                    tags$td("A separator is required, so the two allele sizes can be told apart.")),
            tags$tr(tags$td("Missing"), tags$td(tags$code("00"), ", ", tags$code("NA"), ", ", tags$code("-"), ", ", tags$code("?"), ", blank"),
                    tags$td("All recognised. Missing loci are skipped, not counted against a pair.")),
            tags$tr(tags$td("Allele order"), tags$td(tags$code("AG"), " = ", tags$code("GA")),
                    tags$td("Sorted before comparison, so reversed cells do not become false differences.")),
            tags$tr(tags$td("Quality flags"), tags$td(tags$code("AG*"), ", ", tags$code("CT?")),
                    tags$td("The flag is stripped and the genotype kept. If a flag means “do not trust this”, set those cells to missing before uploading.")))),
        tags$div(class = "m-note",
          tags$b("One column per locus, not two."), " If your file has ",
          tags$code("LOC01a"), " and ", tags$code("LOC01b"), " as separate ",
          "columns — the layout GenAlEx and allelematch use internally — ",
          "join each pair into one column first, for example ", tags$code("AG"),
          " or ", tags$code("120/124"), ". The app converts back to allele pairs ",
          "internally when it hands data to allelematch."),

        .s("What the app does without being asked"),
        tags$table(class = "m-tbl",
          tags$thead(tags$tr(tags$th("Step"), tags$th("What happens"))),
          tags$tbody(
            tags$tr(tags$td("Finds the loci"),
                    tags$td("Columns that parse as diploid genotypes with a consistent alphabet. Shown in the sidebar for you to correct — every column is offerable, so nothing it missed is out of reach.")),
            tags$tr(tags$td("Finds the sample column"),
                    tags$td("Prefers a name that looks like an identifier and ignores columns that are just numbers, such as read counts.")),
            tags$tr(tags$td("Sorts alleles"), tags$td("So allele order never creates a false difference.")),
            tags$tr(tags$td("Drops dead loci"),
                    tags$td("Monomorphic markers, and any below your minimum call rate, are removed and reported.")))),
        tags$div(class = "m-note",
          tags$b("Two things to do yourself."), " Remove species-diagnostic and ",
          "sex markers from the locus list — they are near-fixed within a ",
          "species, so they add no power and distort the frequency model. And set ",
          tags$b("Analyse separately by"), " to your species or population column, ",
          "so samples from different groups are never compared and each group gets ",
          "its own allele frequencies."),

        # ----------------------------------------------------------- notation
        .h("Notation", id = "m-notation"),
        .p("Every symbol used on this page, in one place."),
        tags$table(class = "m-tbl",
          tags$thead(tags$tr(tags$th("Symbol"), tags$th("Means"))),
          tags$tbody(
            tags$tr(tags$td("\\(i, j\\)"), tags$td("Two samples being compared.")),
            tags$tr(tags$td("\\(\\ell\\)"), tags$td("A locus \u2014 one position in the genome that you genotyped.")),
            tags$tr(tags$td("\\(L\\)"), tags$td("The number of loci compared for a given pair. Loci missing in either sample are not compared, so \\(L\\) differs from pair to pair.")),
            tags$tr(tags$td("\\(G_{i\\ell}\\)"),
                    tags$td(tags$b("The observed genotype"), " of sample \\(i\\) at locus \\(\\ell\\) \u2014 the pair of alleles your sequencer or capillary machine actually reported, for example ",
                            tags$code("A/G"), ". This is data. It may be wrong.")),
            tags$tr(tags$td("\\(G_i\\)"), tags$td("Sample \\(i\\)'s whole multilocus genotype: \\(G_{i1}, G_{i2}, \\dots, G_{iL}\\) together.")),
            tags$tr(tags$td("\\(g\\)"),
                    tags$td(tags$b("A true genotype"), " \u2014 what the animal actually carries. You never observe this directly; the methods that use it sum over every possibility it could have been.")),
            tags$tr(tags$td("\\(p_a\\)"), tags$td("The frequency of allele \\(a\\) in the population, estimated from your samples.")),
            tags$tr(tags$td("\\(d\\)"), tags$td("Allelic dropout rate \u2014 the chance a heterozygote is seen as a homozygote.")),
            tags$tr(tags$td("\\(f\\)"), tags$td("False allele rate \u2014 the chance an allele appears that the animal does not carry.")),
            tags$tr(tags$td("\\(\\mathbb{1}[\\,\\cdot\\,]\\)"),
                    tags$td("An ", tags$i("indicator"), ": equals 1 when the statement inside is true and 0 when it is false. Used to count things by adding up 1s.")),
            tags$tr(tags$td("\\(H_1, H_0\\)"), tags$td("The two competing explanations: one animal sampled twice (\\(H_1\\)) versus two different animals (\\(H_0\\)).")))),
        .plain("\\(G\\) is what you measured. \\(g\\) is the truth you are trying to ",
               "recover. Everything on this page is about the gap between them."),

        # ---------------------------------------------------------- example
        .h("A worked example", id = "m-example"),
        .p("One pair of samples, six loci, carried through every method so you can ",
           "see exactly what each one does with the same evidence."),
        .example_table(),
        .p("Two things are going on. At ", tags$b("L1"), " the samples differ: A is ",
           tags$code("A/G"), " and B is ", tags$code("A/A"), ". Notice that they still ",
           tags$i("share"), " the allele ", tags$code("A"), " \u2014 this is exactly the ",
           "pattern dropout produces, because dropout can only turn a heterozygote into a ",
           "homozygote for an allele the animal already carries. At ", tags$b("L6"),
           " sample B was not typed at all, so there is nothing to compare."),
        .p("So across the five loci where both were typed, they differ at one, and that ",
           "one difference is dropout-shaped. Is this one animal or two? Here is what each ",
           "method concludes."),
        tags$table(class = "m-tbl",
          tags$thead(tags$tr(tags$th("Method"), tags$th("Verdict"), tags$th("Because"))),
          tags$tbody(
            tags$tr(tags$td("Exact match"), tags$td(tags$b("two animals")),
                    tags$td("One locus differs, and it allows none.")),
            tags$tr(tags$td("Threshold, \\(k = 1\\)"), tags$td(tags$b("one animal")),
                    tags$td("One differing locus is within the allowance.")),
            tags$tr(tags$td("GenAlEx"), tags$td(tags$b("two animals, flagged")),
                    tags$td("Identification is exact matching, but the pair lands on the near-match list for you to inspect.")),
            tags$tr(tags$td("allelematch"), tags$td(tags$b("depends on \\(\\hat{m}\\)")),
                    tags$td("Similarity works out at 0.833; it needs \\(\\hat{m} = 2\\) to match, because the untyped locus costs as much as the real difference. Worked through below.")),
            tags$tr(tags$td("Likelihood ratio"), tags$td(tags$b("one animal, with a number attached")),
                    tags$td("A shared-allele difference is cheap under dropout and expensive under \u201ctwo animals\u201d, so the pair gains support \u2014 how much depends on \\(d\\) and on how common those alleles are.")))),
        .plain("The methods do not disagree because some are wrong. They disagree ",
               "because they are asking different questions. Exact matching asks ",
               "\u201care these identical?\u201d The likelihood ratio asks \u201cwhich ",
               "explanation fits better, and by how much?\u201d"),

        # --------------------------------------------------------------- prep
        .h("Preparing the data", id = "m-prep"),
        .s("Genotypes are order-normalised"),
        .p("Alleles are sorted inside each genotype, so ", tags$code("T/C"), " and ",
           tags$code("C/T"), " become one genotype. Panels commonly contain a handful of ",
           "reversed cells, and compared as raw text those would count as differences. ",
           "This matters more than it sounds: allelematch compares allele slots by ",
           "position, so unsorted alleles would break it outright."),
        .s("Species-diagnostic and sex markers are excluded"),
        .p("A locus that is nearly fixed between two species carries almost no information ",
           "within either one, and its allele frequencies are meaningless when the two are ",
           "pooled. Use those loci to assign species, then drop them from identification. ",
           "The sex marker is kept aside as an independent check: two samples from one ",
           "animal cannot disagree about sex, so if they do, something is wrong."),
        .s("Analyses are blocked by species or population"),
        .p("Samples in different blocks are never compared, and allele frequencies are ",
           "estimated within each block. Pooling two populations makes the pooled sample ",
           "look more variable than either one really is, which makes every probability ",
           "below wrong in the optimistic direction."),
        .s("Allele frequencies"),
        .p("For a locus with alleles \\(1 \\dots m\\), \\(p_a\\) is the frequency of allele ",
           "\\(a\\), counted across all sampled genotypes. Assuming random mating ",
           "(Hardy-Weinberg), the chance an animal carries a given genotype is"),
        .eq("P(a/a) = p_a^2, \\qquad P(a/b) = 2p_ap_b \\;\\;(a \\neq b)"),
        .p("The factor of 2 is there because a heterozygote can be inherited two ways ",
           "round: \\(a\\) from the mother and \\(b\\) from the father, or the reverse."),
        tags$div(class = "m-note",
          tags$b("Recaptures bias allele frequencies."), " An animal sampled sixteen times ",
          "contributes its genotype sixteen times, which makes its alleles look common. ",
          "This app estimates frequencies once, clusters, then re-estimates weighting each ",
          "sample by the reciprocal of its cluster size, so every animal counts once."),

        # -------------------------------------------------------------- exact
        .h("1. Exact match", id = "m-exact", tag = "baseline", tagclass = "chk"),
        .p("Two samples are the same individual only if every locus where both were ",
           "typed is identical:"),
        .eq("\\text{same individual} \\iff G_{i\\ell} = G_{j\\ell} \\;\\; \\text{for all } \\ell \\text{ where both were typed}"),
        .p("Loci missing in either sample are skipped, and a minimum number of compared ",
           "loci \\(L_{\\min}\\) is required so that a pair sharing only a handful of loci ",
           "is not declared identical on flimsy evidence."),
        .p("With genuinely clean genotypes this is close to correct, and it is a useful ",
           "check: if exact matching agrees with everything else, your data are in good ",
           "shape. Its weakness is that it cannot express doubt. One dropout splits an ",
           "animal in two, and a pair matching on 15 shared loci is treated with exactly ",
           "the same confidence as a pair matching on 40."),

        # ---------------------------------------------------------- threshold
        .h("2. Mismatch threshold", id = "m-thresh", tag = "gut check", tagclass = "chk"),
        .p("The obvious repair to exact matching: allow a few differences. Count how many ",
           "loci differ between the pair,"),
        .eq("M_{ij} \\;=\\; \\sum_{\\ell = 1}^{L} \\mathbb{1}\\!\\left[\\, G_{i\\ell} \\neq G_{j\\ell} \\,\\right]"),
        .p("and call the pair the same animal when \\(M_{ij} \\le k\\), provided at least ",
           "\\(L_{\\min}\\) loci were compared. Reading that formula out loud: for each ",
           "locus \\(\\ell\\), look at sample \\(i\\)'s genotype \\(G_{i\\ell}\\) and sample ",
           "\\(j\\)'s genotype \\(G_{j\\ell}\\); add 1 if they differ and 0 if they agree; ",
           "\\(M_{ij}\\) is the running total."),
        .p("In the worked example, \\(M = 1\\) over \\(L = 5\\) compared loci, so the pair ",
           "matches at \\(k = 1\\) and not at \\(k = 0\\)."),

        .s("Not all differences are equal"),
        .p("A difference where the two genotypes still share an allele \u2014 ",
           tags$code("A/G"), " against ", tags$code("A/A"), " \u2014 is exactly what dropout ",
           "produces. A difference where they share ", tags$i("nothing"), " \u2014 ",
           tags$code("A/A"), " against ", tags$code("G/G"), " \u2014 cannot be caused by ",
           "dropout at all, because dropout only ever removes an allele the animal already ",
           "has. The app counts those separately:"),
        .eq("M^{\\text{hard}}_{ij} \\;=\\; \\sum_{\\ell=1}^{L} \\mathbb{1}\\!\\left[\\, G_{i\\ell} \\cap G_{j\\ell} = \\varnothing \\,\\right]"),
        .p("where \\(G_{i\\ell} \\cap G_{j\\ell} = \\varnothing\\) means the two genotypes have ",
           "no allele in common. A pair with even one hard mismatch is far more likely to ",
           "be two animals, whatever the total count says, so the app reports it as a ",
           "separate column."),

        .s("How to choose k"),
        .p("Not by taste. With a panel that can do the job, the distribution of \\(M\\) ",
           "across all pairs has two humps: a pile near zero (the same animal, sampled ",
           "more than once) and a pile far away (genuinely different animals), with a gap ",
           "between them. Put \\(k\\) in the gap. The Individuals tab draws exactly this ",
           "histogram for your data."),
        .p("If there is no gap, no value of \\(k\\) is defensible, and that is worth ",
           "knowing. The sweep on the Method comparison tab makes it visible: it re-runs ",
           "the analysis for every \\(k\\) from 0 upwards and plots how many individuals ",
           "you get. A flat stretch means the answer is a property of your data. A steady ",
           "slide means \\(k\\) is deciding your result and you should use a method that ",
           "weighs evidence instead."),
        .plain("Counting differences treats every locus as equally surprising. It is ",
               "not: a difference at a locus where almost everyone is the same is far ",
               "more telling than one where the population is evenly split. That is the ",
               "limitation the likelihood methods remove."),

        # ------------------------------------------------------------ genalex
        .h("3. GenAlEx Matches", id = "m-genalex", tag = "familiar", tagclass = "chk"),
        .p("Reproduces the ", tags$b("Multilocus \u2192 Matches"), " routine in GenAlEx ",
           "(Peakall & Smouse 2006, 2012), which many labs already run. It does three ",
           "things."),
        .p(tags$b("(a) It tabulates the match distribution"), " \u2014 how many pairs have ",
           "\\(M = 0\\), how many have \\(M = 1\\), and so on. This is the table GenAlEx ",
           "prints, and it is the same distribution the threshold sweep is built on."),
        .p(tags$b("(b) It identifies individuals by exact match"), " (\\(M = 0\\)), and ",
           "reports pairs one or two loci short as ", tags$i("near matches"), " for you to ",
           "inspect rather than merging them automatically. Near matches are exactly where ",
           "dropout and siblings live, which is why the list is worth reading."),
        .p(tags$b("(c) It reports the probability of identity"), " \u2014 the evidence that ",
           "your panel has enough loci to trust a match at all. For a single locus, the ",
           "chance that two ", tags$i("unrelated"), " animals happen to share a genotype is"),
        .eq("P_{\\mathrm{ID}} = \\sum_{a} p_a^{4} \\;+\\; \\sum_{a}\\sum_{b>a} \\left(2p_ap_b\\right)^{2}"),
        .p("The first term is both animals being the same homozygote (\\(p_a^2\\) each, ",
           "multiplied); the second is both being the same heterozygote. For full siblings, ",
           "who share alleles by descent and so match far more often,"),
        .eq("P_{\\mathrm{ID}\\text{-}\\mathrm{sib}} = 0.25 + 0.5\\sum_a p_a^{2} + 0.5\\left(\\sum_a p_a^{2}\\right)^{2} - 0.25\\sum_a p_a^{4}"),
        .p("Across loci, assuming they are inherited independently, the values multiply:"),
        .eq("P_{\\mathrm{ID}}^{\\text{total}} = \\prod_{\\ell=1}^{L} P_{\\mathrm{ID},\\ell}"),
        .p("A panel is conventionally called adequate once ",
           "\\(P_{\\mathrm{ID}\\text{-}\\mathrm{sib}}\\) falls below 0.01, and comfortable ",
           "below 0.001. Quote the sibling value, not the unrelated one: for social or ",
           "family-structured species it is the honest number, and it is often several ",
           "orders of magnitude larger."),
        tags$div(class = "m-note",
          tags$b("Two cautions on these numbers."), " First, multiplying across loci ",
          "assumes they are independent. Two SNPs on the same amplicon are not, and ",
          "multiplying them overstates your power \u2014 the Data & QC tab reports ",
          "r\u00b2 between loci so you can drop one of any correlated pair before quoting a ",
          "figure. Second, GenAlEx can also report a small-sample-corrected ",
          "\u201cunbiased\u201d P(ID); this app reports the uncorrected Waits et al. (2001) ",
          "estimators above. At realistic sample sizes that difference is far smaller than ",
          "the error introduced by population structure, which neither version accounts for."),

        # ------------------------------------------------------------------ am
        .h("4. allelematch", id = "m-am", tag = "gut check", tagclass = "chk"),
        .p("The published semi-automated method of Galpern et al. (2012). Unlike the ",
           "methods above it does not compare pairs and stop there; it builds a similarity ",
           "score, clusters the samples, and then matches every sample back against the ",
           "cluster representatives. Its distinctive contribution is that it will tell you ",
           "when it ", tags$i("cannot"), " decide, rather than forcing every sample into a ",
           "group."),

        .s("Step 1 \u2014 the similarity score"),
        .p("Each sample is laid out as \\(2L\\) allele slots: two per locus, in sorted ",
           "order. Write \\(a_{ik}\\) for the allele in slot \\(k\\) of sample \\(i\\). The ",
           "similarity between two samples is the fraction of slots that agree,"),
        .eq("S_{ij} \\;=\\; \\frac{1}{2L}\\left( \\sum_{k=1}^{2L} \\mathbb{1}\\!\\left[a_{ik} = a_{jk}\\right] \\;+\\; \\tfrac{1}{2}\\,n^{\\text{miss}}_i \\;+\\; \\tfrac{1}{2}\\,n^{\\text{miss}}_j \\right)"),
        .p("where \\(n^{\\text{miss}}_i\\) counts the slots not typed in sample \\(i\\). The ",
           "dissimilarity used for clustering is \\(D_{ij} = 1 - S_{ij}\\)."),
        .p("The two half-credit terms are how allelematch handles missing data, and they ",
           "have a consequence worth understanding. A slot missing in both samples earns ",
           "\\(\\tfrac12 + \\tfrac12 = 1\\), full credit \u2014 missing matches missing ",
           "perfectly. A slot missing in only one earns \\(\\tfrac12\\), half credit. So an ",
           "untyped locus is neither ignored nor treated as a mismatch: it is scored as ",
           "half a match."),

        .s("Step 2 \u2014 the threshold"),
        .p("You do not set \\(S\\) directly. You set \\(\\hat{m}\\), the number of ",
           "mismatching alleles you are willing to tolerate, and allelematch converts it:"),
        .eq("\\hat{s} \\;=\\; 1 - \\frac{\\hat{m}}{2L}, \\qquad \\text{cutHeight} \\;=\\; 1 - \\hat{s} \\;=\\; \\frac{\\hat{m}}{2L}"),
        .p("A pair counts as a match when \\(S_{ij} \\ge \\hat{s}\\). In the package these ",
           "are the ", tags$code("alleleMismatch"), ", ", tags$code("matchThreshold"), " and ",
           tags$code("cutHeight"), " arguments; you give one and the other two follow."),

        .s("Step 3 \u2014 cluster, then match back"),
        .p("The dissimilarity matrix is clustered by ", tags$b("complete-linkage"),
           " hierarchical clustering and cut with the dynamic hybrid tree cut of Langfelder ",
           "et al., repeating until every cluster reduces to a single representative ",
           "genotype. Every sample is then compared against that set of unique genotypes ",
           "and labelled:"),
        tags$table(class = "m-tbl",
          tags$thead(tags$tr(tags$th("Label"), tags$th("Meaning"))),
          tags$tbody(
            tags$tr(tags$td(tags$code("UNIQUE")), tags$td("This sample is the representative of an individual.")),
            tags$tr(tags$td(tags$code("MATCH")), tags$td("Matches exactly one unique genotype at \\(S \\ge \\hat{s}\\).")),
            tags$tr(tags$td(tags$code("MULTIPLE_MATCH")), tags$td("Matches more than one \u2014 ambiguous, and flagged rather than guessed at.")),
            tags$tr(tags$td(tags$code("UNCLASSIFIED")), tags$td("Matches none. Usually too much missing data to place.")))),
        .p("It also reports \\(P_{\\text{sib}}\\), the chance a matched sample is a sibling ",
           "of the unique genotype rather than a repeat of it, following Wilberg & Dreher ",
           "(2004). The app picks \\(\\hat{m}\\) using the package's own ",
           tags$code("amUniqueProfile"), " optimum, which looks for the point where the ",
           "count of unclassified and ambiguous samples settles."),

        .s("Working the example"),
        .p("Six loci means \\(2L = 12\\) slots. Sample B is untyped at L6, so two slots are ",
           "missing. Counting agreements: L1 contributes 1 of its 2 slots (the shared ",
           "\\(A\\)), L2 to L5 contribute 2 each, and L6 contributes nothing directly but ",
           "earns \\(2 \\times \\tfrac12 = 1\\) from the missing-data term. So"),
        .eq("S = \\frac{(1 + 2 + 2 + 2 + 2) + 1}{12} = \\frac{10}{12} = 0.833"),
        .p("At \\(\\hat{m} = 1\\) the bar is \\(\\hat{s} = 1 - 1/12 = 0.917\\), so the pair ",
           "fails. At \\(\\hat{m} = 2\\) the bar is \\(0.833\\) and it passes, just. Had ",
           "sample B been typed at L6 and matched, \\(S\\) would have been \\(11/12 = ",
           "0.917\\) and the pair would have matched at \\(\\hat{m} = 1\\)."),
        tags$div(class = "m-note",
          tags$b("This is why allelematch over-splits sparse SNP panels."), " One untyped ",
          "locus cost the pair the same as one genuinely mismatching allele. A sample with ",
          "several missing loci can never reach a high \\(\\hat{s}\\) against a complete ",
          "genotype, so it gets pushed into a cluster of its own. The method was designed ",
          "for microsatellites, where tolerating 2 or 3 mismatching alleles out of 20 is ",
          "natural and missing data are rarer. Run it as a check; if it returns many more ",
          "individuals than the other methods, look at your call rates before believing it."),

        # ------------------------------------------------------------------ lr
        .h("5. Likelihood ratio", id = "m-lr", tag = "recommended"),
        .p(class = "m-lead",
          "Instead of counting differences, ask which explanation fits the data better: ",
          "one animal sampled twice, or two different animals. This is the only method ",
          "here that uses an explicit error model, states what it is testing against, and ",
          "returns a probability for every pair."),

        .s("The two hypotheses"),
        tags$div(class = "m-def",
          .p(tags$b("\\(H_1\\):"), " one animal with true genotype \\(g\\), observed twice ",
             "through the error process."),
          .p(tags$b("\\(H_0\\):"), " two animals, with genotypes drawn from the population ",
             "at a stated degree of relatedness.")),

        .s("The error model"),
        .p("An observation is generated from a true genotype in two stages."),
        tags$div(class = "m-def",
          .p(tags$b("Dropout."), " With probability \\(d\\), a true heterozygote ",
             "\\(\\{a,b\\}\\) loses one allele at random and is seen as \\(\\{a,a\\}\\) or ",
             "\\(\\{b,b\\}\\), each with probability \\(d/2\\). Homozygotes are unaffected, ",
             "because losing one of two identical copies changes nothing you can see."),
          .p(tags$b("False allele."), " With probability \\(f\\), one of the two surviving ",
             "alleles, chosen at random, is replaced by an allele drawn from the population.")),
        .p("Write \\(E[G \\mid g]\\) for the resulting probability of observing genotype ",
           "\\(G\\) when the truth is \\(g\\). Then the probability of the observed pair ",
           "under each hypothesis is"),
        .eq("P(G_i, G_j \\mid H_1) \\;=\\; \\sum_{g} P(g)\\, E[G_i \\mid g]\\, E[G_j \\mid g]"),
        .eq("P(G_i, G_j \\mid H_0) \\;=\\; \\sum_{g_1}\\sum_{g_2} P(g_1, g_2)\\, E[G_i \\mid g_1]\\, E[G_j \\mid g_2]"),
        .p("The sums are over every genotype the animal could really have had, each ",
           "weighted by how likely that truth was to begin with. This is what \u201cwe never ",
           "observe \\(g\\)\u201d means in practice: you do not guess it, you average over it."),
        .p("Note that \\(H_1\\) does not require the two observations to be identical. A ",
           "pair differing at one locus is still perfectly consistent with one animal \u2014 ",
           "it just costs likelihood, and how much it costs depends on \\(d\\) and \\(f\\). ",
           "That is the whole difference from a threshold rule."),

        .s("The alternative hypothesis, and why it matters"),
        .p("Two animals related by descent share alleles. Splitting by the number of ",
           "alleles shared identical-by-descent, with probabilities \\(k_0, k_1, k_2\\),"),
        .eq("P(g_1, g_2) = k_0\\,P(g_1)P(g_2) \\;+\\; k_1\\,P_1(g_1,g_2) \\;+\\; k_2\\,P(g_1)\\,\\mathbb{1}[g_1 = g_2]"),
        .p("where the one-allele-shared term sums over the shared allele \\(s\\) and the ",
           "two independently drawn alleles \\(a\\) and \\(b\\):"),
        .eq("P_1(g_1, g_2) = \\sum_{s}\\sum_{a}\\sum_{b} p_s\\,p_a\\,p_b\\; \\mathbb{1}\\!\\left[g_1 = \\{s,a\\}\\right]\\,\\mathbb{1}\\!\\left[g_2 = \\{s,b\\}\\right]"),
        tags$table(class = "m-tbl",
          tags$thead(tags$tr(tags$th("Alternative"), tags$th("\\(k_0\\)"), tags$th("\\(k_1\\)"),
                             tags$th("\\(k_2\\)"), tags$th("Use when"))),
          tags$tbody(
            tags$tr(tags$td("Unrelated"), tags$td("1"), tags$td("0"), tags$td("0"),
                    tags$td("solitary or well-mixed population")),
            tags$tr(tags$td("Half siblings"), tags$td("0.5"), tags$td("0.5"), tags$td("0"),
                    tags$td("moderate family structure")),
            tags$tr(tags$td("Full siblings"), tags$td("0.25"), tags$td("0.5"), tags$td("0.25"),
                    tags$td("packs, prides, litters, colonies")),
            tags$tr(tags$td("Parent\u2013offspring"), tags$td("0"), tags$td("1"), tags$td("0"),
                    tags$td("known pedigree sampling")))),
        .p("For a group-living species the samples competing to be \u201ca different ",
           "animal\u201d are usually packmates, not random members of the population. ",
           "Testing against unrelated animals then overstates the evidence for a match, ",
           "because it is answering an easier question than the one you face. Full siblings ",
           "is the conservative and usually the correct choice."),

        .s("Combining loci"),
        .p("Loci are treated as independent, so evidence adds on the log scale over the ",
           "loci where both samples were typed:"),
        .eq("\\log_{10}\\mathrm{LR} \\;=\\; \\sum_{\\ell \\,:\\, \\text{both typed}} \\log_{10} \\frac{P(G_{i\\ell}, G_{j\\ell} \\mid H_1)}{P(G_{i\\ell}, G_{j\\ell} \\mid H_0)}"),
        .p("Missing loci contribute nothing rather than counting against the pair, which ",
           "is why a minimum number of compared loci is enforced separately. A ",
           "\\(\\log_{10}\\mathrm{LR}\\) of 4 means the one-animal explanation fits ten ",
           "thousand times better than the two-animal one."),

        .s("From evidence to a decision"),
        .p("A likelihood ratio is not a probability. To decide, combine it with a prior ",
           "\\(\\pi\\) that a randomly chosen pair of samples is a recapture:"),
        .eq("\\frac{P(H_1 \\mid G_i, G_j)}{P(H_0 \\mid G_i, G_j)} \\;=\\; \\frac{\\pi}{1-\\pi} \\times \\mathrm{LR}"),
        .p("and accept the match when the resulting posterior probability exceeds your ",
           "cutoff, 0.999 by default. The prior is estimated from the data itself, ",
           "self-consistently: start from one recapture per sample, count how many pairs ",
           "match at that prior, feed the count back as \\(\\pi = (m+1)/\\binom{n}{2}\\), ",
           "and repeat until it stops moving. It converges in a few iterations. You can ",
           "also set it by hand if you have a prior expectation of the recapture rate."),
        tags$div(class = "m-note",
          tags$b("A panel carries a finite amount of evidence."), " The strongest possible ",
          "\\(\\log_{10}\\mathrm{LR}\\) is roughly ",
          "\\(-\\log_{10} P_{\\mathrm{ID}\\text{-}\\mathrm{sib}}\\). Set a posterior cutoff ",
          "above what your loci can supply and nothing matches, so every sample is reported ",
          "as its own individual \u2014 which looks like a result and is not one. The app ",
          "checks your cutoff against the best evidence in your own data and warns you on ",
          "the Individuals tab."),

        # ----------------------------------------------------------- sethi
        .h("6. Sethi et al. (2016)", id = "m-sethi", tag = "recommended"),
        .p(class = "m-lead",
          "The same likelihood machinery as method 5, with two deliberate differences that ",
          "between them remove the two settings people find hardest to justify."),

        .s("It divides by the best competing relationship, not one you chose"),
        .p("Rather than asking you to name the alternative, it computes the likelihood ",
           "under every relationship you are willing to consider and divides by whichever ",
           "explains the pair best:"),
        .eq("\\Lambda \\;=\\; \\frac{L(\\text{same individual} \\mid G_i, G_j)}{\\max\\left\\{ L(\\text{unrelated}),\\; L(\\text{full sib}),\\; L(\\text{parent--offspring}) \\right\\}}"),
        .p("The maximum is taken over the ", tags$b("whole multilocus genotype"),
           ", not locus by locus. A pair is called a match only if one animal beats every ",
           "competing relationship, which is conservative in the right direction and ",
           "removes the \u201cwhich alternative do I assume?\u201d decision entirely. The app ",
           "also reports which relationship came closest for each matched pair \u2014 if one ",
           "dominates, that is the alternative your other analyses should be using."),

        .s("It decides on evidence alone"),
        .p("The paper's rule is simply \\(\\Lambda > 1\\): the match hypothesis has to be ",
           "more likely than the best alternative, and nothing more. No prior, no posterior, ",
           "nothing to tune."),
        .p("That is a real advantage \u2014 there is no prior to argue about \u2014 and a ",
           "real limitation, because it takes no account of how many pairs you are testing. ",
           "With \\(n\\) samples you evaluate \\(\\binom{n}{2}\\) pairs, and a rule with no ",
           "multiplicity control will eventually accept a pair that only looks convincing ",
           "because you looked at thousands. Method 5's posterior rule handles that through ",
           "the prior; this one does not. Raise \\(\\Lambda\\) on large datasets, or run ",
           "both and report the range."),
        .p("Because \\(\\Lambda\\) and method 5 share their numerator, and share their ",
           "denominator too whenever full siblings is the closest competing relationship, ",
           "the two often produce ", tags$i("numerically identical"), " evidence and differ ",
           "only in where they cut. Their clustering step \u2014 compare each sample against ",
           "all others, merge on a match, repeat until memberships stop changing \u2014 is ",
           "exactly the connected components of the match graph described next."),

        # ----------------------------------------------------------- reps
        .h("7. Adding location", id = "m-space", tag = "optional", tagclass = "chk"),
        .s("Augustine, Royle, Linden & Fuller (2020), PNAS 117:17903"),
        .plain("Two scats found a few hundred metres apart are more likely to ",
               "come from one animal than two scats twenty kilometres apart, ",
               "because animals live in home ranges rather than wandering at ",
               "random. That is information, and if the genotypes are ambiguous ",
               "it can settle the question. It can also mislead you, and the ",
               "conditions under which it does are known."),

        .p("Augustine et al. built this into the ", tags$b("genotype spatial ",
           "partial identity model"), " (gSPIM), which estimates identity, ",
           "genotyping error and population density together inside a spatial ",
           "capture-recapture model. On a fisher dataset it recovered 157 hair ",
           "samples that had been thrown away as unidentifiable, and came out ",
           "25% more precise than the standard analysis."),

        .p("genoID does not fit gSPIM. That model needs a detector array and a ",
           "capture-recapture design, and opportunistic scat collection has ",
           "neither. What it does is keep the pairwise part of the idea, which ",
           "costs one multiplication per pair. Where the likelihood-ratio method ",
           "combines a prior with genetic evidence,"),
        .eq("\\text{posterior odds} \\;=\\; \\underbrace{\\frac{\\Pr(\\text{same})}{1-\\Pr(\\text{same})}}_{\\text{prior}} \\times \\underbrace{\\Lambda_{\\text{gen}}}_{\\text{genotypes}}"),
        .p("switching this on inserts a third factor, an ordinary likelihood ",
           "ratio built from the distance ", tags$em("d"), " between the two ",
           "samples:"),
        .eq("\\text{posterior odds} \\;=\\; \\frac{\\Pr(\\text{same})}{1-\\Pr(\\text{same})} \\times \\Lambda_{\\text{gen}} \\times \\underbrace{\\frac{f_{\\text{same}}(d)}{f_{\\text{diff}}(d)}}_{\\Lambda_{\\text{space}}}"),

        .p(tags$b("The numerator."), " If an animal's samples fall around its ",
           "activity centre as a bivariate normal with scale \\(\\sigma\\), then ",
           "the separation between two of its samples is bivariate normal with ",
           "scale \\(\\sigma\\sqrt{2}\\), and the distance between them follows a ",
           "Rayleigh distribution:"),
        .eq("f_{\\text{same}}(d) \\;=\\; \\frac{d}{2\\sigma^{2}}\\exp\\!\\left(-\\frac{d^{2}}{4\\sigma^{2}}\\right)"),

        .p(tags$b("The denominator."), " The distance between samples from two ",
           "different animals depends on how the animals are spread out and on ",
           "where you happened to walk. Neither is known, and guessing at them ",
           "would bias every pair in the same direction. So it is not modelled: ",
           "it is read off the data, as a kernel density estimate over the ",
           "distances of the pairs the genetics has already ruled out ",
           "(posterior below \\(10^{-6}\\)). The kernel is fitted on ",
           "\\(\\log d\\) so the density stays positive and sensible far out in ",
           "the tail, where a linear-scale estimate would fall to zero and hand ",
           "a distant pair an absurd likelihood ratio."),

        .p(tags$b("Where \\(\\sigma\\) comes from."), " Also the data. The pairs ",
           "the genetics has already matched give the spread of within-animal ",
           "distances, and the Rayleigh maximum-likelihood estimate is"),
        .eq("\\hat{\\sigma} \\;=\\; \\sqrt{\\tfrac{1}{4}\\,\\overline{d^{2}}}"),
        .p("taken over confidently matched pairs. Both halves of ",
           "\\(\\Lambda_{\\text{space}}\\) are therefore estimated from the two ",
           "confident tails and applied only to the uncertain middle. That is ",
           "empirical Bayes, not a full Bayesian treatment, and it should be ",
           "described that way in a methods section. \\(\\Lambda_{\\text{space}}\\) ",
           "is capped at \\(10^{\\pm 3}\\) so that location can tip a marginal ",
           "call but never overrule the genotypes outright."),

        .p(tags$b("When it helps, and when it does not."), " This is the part ",
           "worth reading twice. Twenty simulated replicates per row, scored ",
           "against known truth by adjusted Rand index:"),
        tags$table(class = "m-ex",
          tags$thead(tags$tr(
            tags$th("Scenario"), tags$th("Genetics"), tags$th("With location"),
            tags$th("Better"), tags$th("Worse"))),
          tags$tbody(
            tags$tr(tags$td("3% dropout, tight home ranges"), tags$td("0.999"),
                    tags$td("1.000"), tags$td("1"), tags$td("0")),
            tags$tr(tags$td("10% dropout, tight home ranges"), tags$td("0.999"),
                    tags$td("1.000"), tags$td("1"), tags$td("0")),
            tags$tr(class = "hi",
                    tags$td("20% dropout, tight home ranges"), tags$td("0.979"),
                    tags$td(tags$b("0.995")), tags$td(tags$b("9")), tags$td("1")),
            tags$tr(tags$td("20% dropout, high overlap"), tags$td("0.979"),
                    tags$td("0.980"), tags$td("3"), tags$td("3")),
            tags$tr(tags$td("20% dropout, total overlap"), tags$td("0.979"),
                    tags$td("0.977"), tags$td("0"), tags$td("2")))),

        .p("Location earns its place in one situation: when dropout is bad ",
           "enough to leave the genotypes ambiguous ", tags$b("and"), " home ",
           "ranges are small compared with the area you sampled. Where the ",
           "genetics is already clean it changes nothing, because there is ",
           "nothing left to decide. Where home ranges overlap heavily, ",
           "\\(f_{\\text{same}}\\) and \\(f_{\\text{diff}}\\) stop being ",
           "distinguishable, the ratio becomes noise, and the last row is a ",
           "small net loss. This is the same condition the authors state: ",
           "spatial information is informative when home-range overlap is low."),

        .plain("Use it when your animals hold distinct territories and you ",
               "sampled across many of them. Do not use it for a species that ",
               "roams, for a dataset collected inside one home range, or when ",
               "the genetics is already decisive \u2014 in the first two cases it ",
               "can quietly merge two animals, and in the third it buys you ",
               "nothing."),

        .p(tags$b("How to check before you trust it."), " The Individuals tab ",
           "reports the estimated \\(\\hat{\\sigma}\\), how many matched pairs it ",
           "was calibrated on, and the median distance apart of matched versus ",
           "ruled-out pairs. If those two medians are close together, your ",
           "animals are not spatially separable and the term should stay off. ",
           "A useful rule of thumb is that ruled-out pairs should sit at least ",
           "three times further apart than matched ones. Run it both ways and ",
           "report the difference: if switching it on changes your answer, that ",
           "belongs in the paper rather than hidden in a setting."),

        .p(tags$b("What it is not."), " This is not gSPIM. It does not estimate ",
           "density, does not model detection, does not propagate identity ",
           "uncertainty into an abundance estimate, and does not use the ",
           "spatial arrangement of everything else in the dataset to inform a ",
           "given pair. If you have a designed array and want those things, fit ",
           "the real model \u2014 the code is at ",
           tags$a(href = "https://github.com/benaug/genotype-SPIM", target = "_blank",
                  rel = "noopener", "github.com/benaug/genotype-SPIM"), "."),

        .h("Using PCR replicates instead of a consensus", id = "m-reps",
           tag = "recommended", tagclass = "rec"),
        .p(class = "m-lead",
          "Most labs genotype each sample two or three times and then collapse ",
          "those replicates into one consensus call before any analysis. That ",
          "collapse is a decision, and every decision throws information away. ",
          "The likelihood methods do not need it."),
        .p("Consider a locus where two replicates said ", tags$code("A/G"),
           " and the third said ", tags$code("A/A"), ". The consensus is ",
           tags$code("A/G"), ", and the fact that one reaction dropped an allele ",
           "is gone. Now consider a locus the consensus rule refused to call: it ",
           "becomes missing, and all three observations are gone, even though ",
           "they said something."),

        .s("The model barely changes"),
        .p("Methods 5 and 6 already integrate over the unknown true genotype, so ",
           "they can condition on every observation just as easily as on one ",
           "summary of them. For sample \\(i\\) at locus \\(\\ell\\) with replicate ",
           "observations \\(o_1 \\dots o_R\\), define the ",
           tags$b("genotype likelihood")),
        .eq("\\mathcal{L}_{i\\ell}(g) = \\prod_{r=1}^{R} P(o_r \\mid g)"),
        .p("which says how well each candidate true genotype \\(g\\) explains ",
           "everything that reaction series produced. The two hypotheses then ",
           "become, with \\(\\mathcal{L}\\) in place of a single observation,"),
        .eq("P(H_1)_{\\ell} = \\sum_{g} P(g)\\,\\mathcal{L}_{i\\ell}(g)\\,\\mathcal{L}_{j\\ell}(g)"),
        .eq("P(H_0)_{\\ell} = \\sum_{g_1}\\sum_{g_2} P(g_1, g_2)\\,\\mathcal{L}_{i\\ell}(g_1)\\,\\mathcal{L}_{j\\ell}(g_2)"),
        .p("Everything downstream \\u2014 summing over loci, the alternative ",
           "hypothesis, the posterior, the clustering \\u2014 is unchanged. The ",
           "consensus route is simply the special case \\(R = 1\\)."),
        .plain("A sample with no observation at a locus gets ",
               "\\(\\mathcal{L} = 1\\) for every \\(g\\), which makes \\(H_1\\) and ",
               "\\(H_0\\) collapse to the same number and contribute exactly zero ",
               "evidence. Missing data needs no special rule; it simply says nothing."),
        tags$div(class = "m-note",
          tags$b("The error rates mean something different here."), " With ",
          "replicates you supply the ", tags$i("per-reaction"), " dropout and ",
          "false-allele rates, typically a few percent. With consensus genotypes ",
          "you supply the much smaller residual rates that survive the multi-tube ",
          "rule, often a few tenths of a percent. Using per-reaction rates on ",
          "consensus calls, or the reverse, is the easiest way to get this wrong."),

        .s("Does it actually help?"),
        .p("Simulating individuals, sampling them, and generating replicates with ",
           "known error rates lets you score both routes against the truth. Across ",
           "180 simulations spanning 20 to 40 loci and 3% to 25% dropout, the ",
           "replicate route landed closer to the true number of animals in 114 ",
           "cases, the consensus route in 3, and they tied in 63."),
        .p("The gain is not uniform. It appears exactly where you are marginal:"),
        tags$table(class = "m-tbl",
          tags$thead(tags$tr(tags$th("Situation"), tags$th("What replicates buy"))),
          tags$tbody(
            tags$tr(tags$td("Plenty of loci, low dropout"),
                    tags$td("Nothing measurable. Both routes already recover the truth; you are simply further from the edge.")),
            tags$tr(tags$td("Marginal panel, or high dropout"),
                    tags$td("A great deal. At 30 loci and 25% dropout, agreement with the truth rose from 0.73 to 0.97.")),
            tags$tr(tags$td("Too few loci for the job"),
                    tags$td("Not enough. Neither route works, because replicates cannot manufacture information the panel never had.")))),
        .p("What improves unconditionally is the ", tags$b("margin"), ": the gap ",
           "between the weakest true recapture and the strongest coincidental ",
           "match. Across every condition tested that gap roughly doubled, for ",
           "instance from 25 to 49 orders of magnitude at 40 loci. A wider margin ",
           "does not change an answer that was already right, but it means the ",
           "answer survives a worse choice of threshold."),
        tags$div(class = "m-note",
          tags$b("Only methods 5 and 6 can do this."), " Exact matching, the ",
          "mismatch threshold, GenAlEx and allelematch all compare one genotype ",
          "per sample and have nowhere to put a second observation. When you turn ",
          "replicates on, those four keep running on a consensus computed with the ",
          "multi-tube rule, so the comparison tab stays meaningful."),

        # --------------------------------------------------------------- graph
        .h("From matched pairs to individuals", id = "m-graph"),
        .p("Every method produces a set of matching pairs. Turning that into a list of ",
           "animals means treating samples as points and matches as lines between them, ",
           "then deciding what counts as a group."),
        tags$div(class = "m-def",
          .p(tags$b("Single linkage"), " (connected components). If A matches B and B ",
             "matches C, all three are one animal even if A and C were never matched ",
             "directly. This recovers recaptures linked through an intermediate sample, but ",
             "one wrong match merges two animals."),
          .p(tags$b("Complete linkage"), " (maximal cliques). Every member must match every ",
             "other member. Conservative; splits a group when one pair happens to fall ",
             "below threshold because of missing data.")),
        .p("Run both. If the answer moves, some clusters are held together by a single ",
           "match and deserve a look. The app always reports ",
           tags$b("internally inconsistent clusters"), " \u2014 groups where some members do ",
           "not match each other \u2014 with their completeness, the fraction of ",
           "within-cluster pairs that actually matched. A cluster below 1.0 is the single ",
           "most useful diagnostic on the page."),

        # ----------------------------------------------------------------- err
        .h("Measuring your own error rates", id = "m-err"),
        .p(class = "m-lead",
          "The likelihood methods need a dropout rate \\(d\\) and a false-allele ",
          "rate \\(f\\). Guessing them is the weakest link in the whole analysis, ",
          "and you almost never have to: the data usually contain enough to ",
          "measure them. Press ", tags$b("Estimate these from my data"),
          " in the sidebar and the app picks the best method your data supports."),

        .s("Best: from PCR replicates, by maximum likelihood"),
        .p("If any samples were genotyped more than once, the replicates ",
           "disagree exactly as often as the error rates say they should. Treat ",
           "the true genotype at each sample and locus as unknown, average over ",
           "it, and maximise over the two rates. For replicate observations ",
           "\\(o_1 \\dots o_R\\),"),
        .eq("\\mathcal{L}(d, f) = \\prod_{\\text{sample},\\,\\text{locus}} \\; \\sum_{g} P(g) \\prod_{r=1}^{R} P(o_r \\mid g, d, f)"),
        .p("This never looks at a consensus, so nothing is circular, and it ",
           "returns profile-likelihood confidence intervals so you can see how ",
           "well pinned down the numbers are. On the AITRC panel it gives a ",
           "dropout rate of 2.9% [2.5-3.4] and a false-allele rate of 1.5% ",
           "[1.3-1.7] per reaction."),
        .plain("Two replicates on a subset of samples is enough. You do not need ",
               "to replicate everything, and the app uses whatever replicates ",
               "exist even if you are analysing consensus calls."),

        .s("The trap: scoring replicates against a consensus"),
        .p("The textbook approach (Broquet & Petit 2004) compares each replicate ",
           "to a reference genotype and counts disagreements:"),
        .eq("\\hat{d} = \\frac{\\#\\{\\text{true het scored as hom}\\}}{\\#\\{\\text{true het}\\}}, \\qquad \\hat{f} = \\frac{\\#\\{\\text{true hom carrying a foreign allele}\\}}{\\#\\{\\text{true hom}\\}}"),
        tags$div(class = "m-note",
          tags$b("This breaks when the reference is your own consensus."), " If ",
          "the consensus calls a homozygote only when all replicates agree, then ",
          "no replicate can ever be seen disagreeing with a homozygous consensus, ",
          "and \\(\\hat{f}\\) is forced to exactly zero. On the AITRC data this ",
          "estimator returns a false-allele rate of 0.00% while the maximum ",
          "likelihood estimator, given the same replicates, returns 1.5%. The ",
          "estimator is measuring its own reference, not the assay."),

        .s("No replicates? Approximate it from the heterozygote deficit"),
        .p("Dropout turns heterozygotes into homozygotes, so it leaves a ",
           "signature: fewer heterozygotes than random mating predicts. Comparing ",
           "observed heterozygosity \\(H_o\\) with expected \\(H_e\\),"),
        .eq("H_o \\approx H_e\\,(1 - d) \\quad\\Longrightarrow\\quad \\hat{d} \\approx 1 - \\frac{H_o}{H_e} = F_{IS}"),
        tags$div(class = "m-note",
          tags$b("Know what this is and is not."), " It is the right order of ",
          "magnitude, not a number to report, and it is not a guaranteed ceiling ",
          "either. Inbreeding, population structure and null alleles all reduce ",
          "heterozygosity and push the figure up: on the AITRC panel it returns ",
          "6.0% against a measured 2.9%. But false alleles push the other way by ",
          "manufacturing heterozygotes, and on a simulated panel built with 3.0% ",
          "dropout it returned 2.6% \u2014 under the truth. The false-allele ",
          "rate cannot be got this way at all."),
        .p("It is still useful two ways: to set the centre of a sensitivity ",
           "analysis, and per locus. A single marker with a large deficit is usually a ",
           "genuine assay problem — a null allele or a primer-site mutation ",
           "— rather than population biology, and is worth dropping. The Data ",
           "& QC tab reports \\(F_{IS}\\) per locus for exactly this."),

        .s("Per reaction or per genotype? They differ by orders of magnitude"),
        .p("This is the easiest thing to get wrong. A multi-tube consensus rule ",
           "— heterozygote accepted on two replicates, homozygote only on ",
           "three — turns a few percent dropout per reaction into a small ",
           "fraction of a percent in the consensus call:"),
        tags$table(class = "m-tbl",
          tags$thead(tags$tr(tags$th("What you are analysing"), tags$th("Rate to supply"),
                             tags$th("AITRC panel"))),
          tags$tbody(
            tags$tr(tags$td("Raw PCR replicates"), tags$td("Per reaction"),
                    tags$td("dropout 0.029, false allele 0.015")),
            tags$tr(tags$td("Consensus calls"), tags$td("Residual after the consensus rule"),
                    tags$td("dropout 0.0001, false allele 0.0007")),
            tags$tr(tags$td("Single-pass genotypes"), tags$td("Per reaction"),
                    tags$td("as the replicate row")))),
        .p("A factor of roughly three hundred separates those two dropout rates. ",
           "The app converts for you: it always measures per-reaction rates from ",
           "your replicates, then, if you are analysing consensus calls, runs ",
           tags$code("gid_propagate_error()"), " to simulate your consensus rule ",
           "and fills the sliders with the residual rate instead."),

        .s("If you can only guess"),
        .p("Set the rates from the literature for your marker type and sample ",
           "material, then use the sensitivity panel on the Method comparison tab ",
           "to see whether it matters. On a comfortable panel it usually does not: ",
           "the AITRC answer moves by one animal across a hundredfold change in ",
           "assumed dropout. On a marginal panel it does, and then measuring the ",
           "rates proper is no longer optional."),
        .plain("Overstating your error rate is the safer mistake. It makes the ",
               "method more forgiving of differences, so it merges more readily; ",
               "understating it splits one animal into several. Neither is free, ",
               "but a split is easier to spot afterwards than a merge."),

        # -------------------------------------------------------------- cutoff
        .h("Choosing the posterior cutoff", id = "m-cutoff"),
        .p(class = "m-lead",
          "This is the setting people find hardest to justify, because 0.999 is ",
          "a convention rather than a result. It does not have to be a guess: the ",
          "method already gives every pair a probability, so the cost of any ",
          "cutoff can be added up directly."),
        tags$div(class = "m-note",
          tags$b("If you want the short answer: "), "the Individuals tab runs ",
          "the procedure below on your own data and prints a recommended cutoff ",
          "with a button to apply it. What follows is what that recommendation ",
          "is doing, so you can defend it or overrule it."),

        .s("Count the mistakes each cutoff would make"),
        .p("Accepting a pair with posterior \\(p\\) means accepting a chance ",
           "\\(1-p\\) that you have just merged two different animals. Rejecting ",
           "one means accepting a chance \\(p\\) that you have split a single ",
           "animal in two. Summing over pairs,"),
        .eq("E[\\text{false merges}] = \\sum_{\\text{accepted}} (1 - p_{ij}), \\qquad E[\\text{missed pairs}] = \\sum_{\\text{rejected}} p_{ij}"),
        .p("Both are in the same units \\u2014 numbers of pairs \\u2014 so the ",
           "cutoff becomes a stated trade instead of a habit. The Individuals tab ",
           "plots both curves against the cutoff for your data."),
        .plain("The two errors are not symmetric in their consequences. A false ",
               "merge loses an animal and biases abundance down. A split invents ",
               "one, biases abundance up, and manufactures a spurious ",
               "“caught once” record \\u2014 which is exactly the ",
               "quantity most capture-recapture estimators are most sensitive to. ",
               "For abundance work, splitting is usually the more damaging ",
               "direction."),

        .s("What this looks like in practice"),
        .p("On the AITRC panel, every cutoff from 0.5 to 0.9995 costs less than ",
           "one expected false merge in the whole dataset, while the individual ",
           "count moves only from 55 to 59. Within that range the cutoff is ",
           "barely doing any work, and the honest report is the range."),
        .p("Push it to 0.99999 and the answer jumps to 104 animals \\u2014 every ",
           "sample its own individual. That is not caution. It buys a reduction ",
           "of 0.02 in expected false merges and pays 241 expected missed pairs ",
           "for it."),
        tags$div(class = "m-note",
          tags$b("Every sample coming back as a unique individual is a symptom, ",
                 "not a result."), " It nearly always means the cutoff is above ",
          "what the panel can supply. A panel carries a finite amount of ",
          "evidence: the best possible \\(\\log_{10}\\mathrm{LR}\\) is roughly ",
          "\\(-\\log_{10} P_{\\mathrm{ID}\\text{-}\\mathrm{sib}}\\), and once the ",
          "prior is folded in there is a maximum posterior no pair can exceed. ",
          "The app reports that ceiling and suggests a workable cutoff instead."),

        .s("A defensible procedure"),
        tags$table(class = "m-tbl",
          tags$thead(tags$tr(tags$th("Step"), tags$th("What to do"))),
          tags$tbody(
            tags$tr(tags$td("1"), tags$td("Check the ceiling. If the best pair in your data cannot reach your cutoff, nothing else matters \\u2014 lower it or add loci.")),
            tags$tr(tags$td("2"), tags$td("Set an error budget in pairs, not a probability. \\u201cI will tolerate under one expected false merge\\u201d is a defensible sentence; \\u201cI used 0.999\\u201d is not.")),
            tags$tr(tags$td("3"), tags$td("Find the plateau: the widest run of cutoffs inside the budget that all return the same number of individuals. Inside one, the answer is a property of the data rather than of the setting.")),
            tags$tr(tags$td("4"), tags$td("Sit in the middle of it. The middle is the value least sensitive to your error rates being somewhat wrong; the edges are where the answer is about to change. This is what the app recommends.")),
            tags$tr(tags$td("5"), tags$td("Report the range, not just the point. \\u201c55 to 59 animals across every defensible cutoff\\u201d is more informative, and more honest, than a single number.")))),
        .plain("A stricter cutoff is not a safer one. Being stricter than your ",
               "budget requires buys a fraction of a false merge and pays for it ",
               "in lost recaptures \u2014 on the example data, moving from 0.95 to ",
               "0.999 saves 0.17 expected false merges and discards 21.8 real ",
               "recapture pairs, for exactly the same number of animals. The ",
               "count survives because of transitivity; the capture histories ",
               "underneath it do not, and those are what an abundance estimator ",
               "actually consumes."),
        .s("Where to start, if you want a number"),
        .p("These are starting points, not answers. Run the calibration and let ",
           "your data move you off them \u2014 the whole point is that the right ",
           "value depends on your panel, your error rates and how many pairs you ",
           "are comparing."),
        tags$table(class = "m-tbl",
          tags$thead(tags$tr(tags$th("Situation"), tags$th("Start at"),
                             tags$th("Why"))),
          tags$tbody(
            tags$tr(tags$td("Dense SNP panel, 30+ loci, low dropout"),
                    tags$td("0.999"),
                    tags$td("Evidence is plentiful; the cutoff usually sits on a wide plateau and barely matters.")),
            tags$tr(tags$td("Microsatellites, 8\u201312 loci"),
                    tags$td("0.99"),
                    tags$td("Less evidence per pair, so a strict cutoff starts rejecting real recaptures before it buys much.")),
            tags$tr(tags$td("Degraded samples, dropout above 10%"),
                    tags$td("0.95\u20130.99"),
                    tags$td("Posteriors are flattened by the error model; holding out for 0.999 mostly splits animals.")),
            tags$tr(tags$td("Thousands of samples"),
                    tags$td("higher, and set the budget"),
                    tags$td("Expected false merges scale with the number of pairs compared, so the same cutoff costs more mistakes.")),
            tags$tr(tags$td("Close kin expected in the sample"),
                    tags$td("keep 0.999, change the null"),
                    tags$td("The fix for relatives is a full-sibling alternative, not a stricter cutoff.")))),
        .plain("The number of pairs matters more than people expect. Comparing ",
               "100 samples means about 5,000 pairs; comparing 1,000 means about ",
               "500,000. At the same cutoff the second study accepts a hundred ",
               "times as much accumulated risk, which is why an error budget in ",
               "pairs travels between studies and a probability does not."),

        .s("What to write in the paper"),
        .p("Something close to: \u201cSamples were assigned to individuals using a ",
           "likelihood-ratio test against a full-sibling alternative, with ",
           "dropout and false-allele rates estimated from PCR replicates by ",
           "maximum likelihood. The posterior cutoff was chosen as the most ",
           "permissive value expected to produce fewer than one false merge ",
           "across all pairwise comparisons; the resulting count was stable ",
           "across cutoffs from X to Y.\u201d That sentence states the criterion, ",
           "the budget and the sensitivity, which is everything a reader needs ",
           "and rather more than \u201cwe used 0.999\u201d."),

        tags$div(class = "m-note",
          tags$b("Two caveats on the error counts."), " Pairs are not independent ",
          "\\u2014 one accepted pair can merge a whole cluster through ",
          "transitivity \\u2014 so these are pair-level counts, not ",
          "individual-level ones. And they trust the model's own posteriors, so ",
          "they inherit whatever is wrong with your error rates and your choice ",
          "of alternative hypothesis. Read them next to the sensitivity grid, ",
          "not instead of it."),

        # ----------------------------------------------------------------- set
        .h("Choosing settings", id = "m-set"),
        tags$table(class = "m-tbl",
          tags$thead(tags$tr(tags$th("Setting"), tags$th("What it does"), tags$th("Guidance"))),
          tags$tbody(
            tags$tr(tags$td("Alternative hypothesis"),
                    tags$td("What \u201ctwo different animals\u201d means"),
                    tags$td("Full siblings for group-living species. Usually the setting that moves the answer most.")),
            tags$tr(tags$td("Posterior cutoff"),
                    tags$td("Confidence required to accept a match"),
                    tags$td("0.999 is a reasonable default. Check the warning that your panel can actually reach it.")),
            tags$tr(tags$td("Dropout, false allele"),
                    tags$td("The error model"),
                    tags$td("Measure from replicates if you can. For multi-replicate consensus genotypes both are usually well under 0.005.")),
            tags$tr(tags$td("Mismatch threshold \\(k\\)"),
                    tags$td("Loci allowed to differ"),
                    tags$td("Put it in the gap in the mismatch histogram. If there is no gap, use a likelihood method.")),
            tags$tr(tags$td("\\(\\hat{m}\\) (allelematch)"),
                    tags$td("Mismatching alleles tolerated"),
                    tags$td("Left to the package's own profile by default. Remember each untyped locus costs half a locus of similarity.")),
            tags$tr(tags$td("Minimum loci per pair"),
                    tags$td("Refuses to judge sparse comparisons"),
                    tags$td("Set so the loci compared could reach your cutoff on their own; the per-sample power plot shows which samples cannot.")),
            tags$tr(tags$td("Cluster rule"), tags$td("Single vs complete linkage"),
                    tags$td("Run both; report the difference if there is one.")))),
        .p("Then use the sensitivity panel on the Method comparison tab. It re-runs the ",
           "whole analysis across a grid of these settings. If the individual count barely ",
           "moves, it is a property of your data; if it swings, it is a property of your ",
           "choices, and the range belongs in your results."),

        # ------------------------------------------------------------ glossary
        .h("Glossary of every column", id = "m-glossary"),
        .p("Every quantity the app can show you, what it means, and the column name ",
           "it carries in downloaded files. Tables in the app show the plain-English ",
           "label; hover any column header to see its definition without coming back here."),
        gid_glossary_ui(),

        # ---------------------------------------------------------------- refs
        .h("References", id = "m-refs"),
        tags$div(class = "m-def", style = "font-size:.88rem;",
          .p("Broquet, T. & Petit, E. (2004). Quantifying genotyping errors in noninvasive ",
             "population genetics. ", tags$i("Molecular Ecology"), " 13, 3601\u20133608."),
          .p("Galpern, P., Manseau, M., Hettinga, P., Smith, K. & Wilson, P. (2012). ",
             "allelematch: an R package for identifying unique multilocus genotypes where ",
             "genotyping error and missing data may be present. ",
             tags$i("Molecular Ecology Resources"), " 12, 771\u2013778."),
          .p("Langfelder, P., Zhang, B. & Horvath, S. (2008). Defining clusters from a ",
             "hierarchical cluster tree: the Dynamic Tree Cut package. ",
             tags$i("Bioinformatics"), " 24, 719\u2013720."),
          .p("Paetkau, D. (2003). An empirical exploration of data quality in DNA-based ",
             "population inventories. ", tags$i("Molecular Ecology"), " 12, 1375\u20131387."),
          .p("Peakall, R. & Smouse, P.E. (2006, 2012). GenAlEx 6: genetic analysis in Excel. ",
             tags$i("Molecular Ecology Notes"), " 6, 288\u2013295; ", tags$i("Bioinformatics"),
             " 28, 2537\u20132539."),
          .p("Sethi, S.A., Linden, D., Wenburg, J., Lewis, C., Lemons, P., Fuller, A. & ",
             "Hare, M.P. (2016). Accurate recapture identification for genetic ",
             "mark\u2013recapture studies with error-tolerant likelihood-based match calling ",
             "and sample clustering. ", tags$i("Royal Society Open Science"), " 3, 160457."),
          .p("Taberlet, P. et al. (1996). Reliable genotyping of samples with very low DNA ",
             "quantities using PCR. ", tags$i("Nucleic Acids Research"), " 24, 3189\u20133194."),
          .p("Waits, L.P., Luikart, G. & Taberlet, P. (2001). Estimating the probability of ",
             "identity among genotypes in natural populations: cautions and guidelines. ",
             tags$i("Molecular Ecology"), " 10, 249\u2013256."),
          .p("Wilberg, M.J. & Dreher, B.P. (2004). GENECAP: a program for analysis of ",
             "multilocus genotype data for non-invasive sampling and capture-recapture ",
             "population estimation. ", tags$i("Molecular Ecology Notes"), " 4, 783\u2013785."))
      ))
    )
  )
}
